name: tapir
version: 1.0.0
github: "yourusername/tapir"
license: MIT
author: "Dani Cusanelli"
maintainer: "your@email.com"
copyright: "2026 Dani Cusanelli"

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis: Language-agnostic terminal-based language learning assistant
category: Education

description: |
  TAPIR (Translation API Router) is a keyboard-driven TUI for language learning
  with conversation practice, grammar correction, translation, and Anki integration.

dependencies:
  # Core
  - base >= 4.17 && < 5
  - text >= 2.0 && < 2.2
  - bytestring >= 0.11 && < 0.13
  - containers >= 0.6 && < 0.8
  - time >= 1.12 && < 1.15
  - uuid >= 1.3 && < 1.4

  # TUI
  - brick >= 2.1 && < 2.5
  - vty >= 6.0 && < 6.3
  - vty-unix >= 0.2 && < 0.3
  - microlens >= 0.4 && < 0.5
  - microlens-th >= 0.4 && < 0.5

  # HTTP & JSON
  - req >= 3.13 && < 3.14
  - aeson >= 2.1 && < 2.3
  - aeson-pretty >= 0.8 && < 0.9
  - http-client >= 0.7 && < 0.8
  - http-types >= 0.12 && < 0.13

  # Database
  - sqlite-simple >= 0.4 && < 0.5

  # Config & CLI
  - optparse-applicative >= 0.18 && < 0.19
  - directory >= 1.3 && < 1.4
  - filepath >= 1.4 && < 1.6
  - yaml >= 0.11 && < 0.12

  # Utilities
  - mtl >= 2.3 && < 2.4
  - transformers >= 0.6 && < 0.7
  - exceptions >= 0.10 && < 0.11
  - async >= 2.2 && < 2.3
  - stm >= 2.5 && < 2.6
  - word-wrap >= 0.5 && < 0.6
  - vector >= 0.13 && < 0.14
  - unordered-containers >= 0.2 && < 0.3

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wpartial-fields
  - -Wredundant-constraints
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - RecordWildCards
  - LambdaCase
  - TypeApplications

library:
  source-dirs: src

executables:
  tapir:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -O2
    dependencies:
      - tapir

tests:
  tapir-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tapir
      - hspec >= 2.10 && < 2.12
      - hspec-discover >= 2.10 && < 2.12
      - QuickCheck >= 2.14 && < 2.16
