{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}

-- |
-- Module      : Tapir.Model.Anki
-- Description : Anki flashcard domain types
-- Copyright   : (c) 2026 Dani Cusanelli
-- License     : MIT

module Tapir.Model.Anki
  ( AnkiCard(..)
  ) where

import Data.Aeson
import Data.Text (Text)
import Data.Time (UTCTime)
import GHC.Generics (Generic)

-- | Anki flashcard
-- Note: ID is auto-generated by SQLite (INTEGER PRIMARY KEY AUTOINCREMENT)
data AnkiCard = AnkiCard
  { cardId          :: !(Maybe Int)     -- Nothing for new cards, Just for persisted
  , cardSessionId   :: !Text            -- FK to session
  , cardLanguageId  :: !Text
  , cardFront       :: !Text
  , cardBack        :: !Text
  , cardTags        :: ![Text]          -- Stored as JSON array in DB
  , cardDeck        :: !Text
  , cardSourceMsgId :: !(Maybe Int)     -- Source message that generated this card
  , cardAnkiNoteId  :: !(Maybe Integer) -- AnkiConnect note ID after push
  , cardPushedAt    :: !(Maybe UTCTime) -- When pushed to Anki
  , cardCreatedAt   :: !UTCTime
  } deriving (Eq, Show, Generic)

instance ToJSON AnkiCard
instance FromJSON AnkiCard
