{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE LambdaCase #-}

-- |
-- Module      : Tapir.Model.Chat
-- Description : Chat domain types (Session, Message, Role)
-- Copyright   : (c) 2026 Dani Cusanelli
-- License     : MIT

module Tapir.Model.Chat
  ( -- * Role
    Role(..)
  , roleToText
  , textToRole

    -- * Message
  , Message(..)

    -- * Session
  , Session(..)
  ) where

import Data.Aeson
import Data.Text (Text)
import qualified Data.Text as T
import Data.Time (UTCTime)
import GHC.Generics (Generic)

import Tapir.Types.Mode (Mode)
import Tapir.Types.Language (LearnerLevel)

-- ════════════════════════════════════════════════════════════════
-- ROLE
-- ════════════════════════════════════════════════════════════════

-- | Message role in conversation
data Role = User | Assistant | System
  deriving (Eq, Show, Generic)

instance ToJSON Role where
  toJSON = String . roleToText

instance FromJSON Role where
  parseJSON = withText "Role" $ \case
    "user"      -> pure User
    "assistant" -> pure Assistant
    "system"    -> pure System
    other       -> fail $ "Unknown role: " <> T.unpack other

-- | Convert Role to Text for database storage
roleToText :: Role -> Text
roleToText = \case
  User      -> "user"
  Assistant -> "assistant"
  System    -> "system"

-- | Parse Role from Text
textToRole :: Text -> Maybe Role
textToRole = \case
  "user"      -> Just User
  "assistant" -> Just Assistant
  "system"    -> Just System
  _           -> Nothing

-- ════════════════════════════════════════════════════════════════
-- MESSAGE
-- ════════════════════════════════════════════════════════════════

-- | Chat message (stored in database)
-- Note: ID is auto-generated by SQLite (INTEGER PRIMARY KEY AUTOINCREMENT)
data Message = Message
  { messageId         :: !(Maybe Int)  -- Nothing for new messages, Just for persisted
  , messageSessionId  :: !Text         -- UUID as text
  , messageRole       :: !Role
  , messageContent    :: !Text
  , messageMode       :: !Mode         -- The mode this message was sent in
  , messageTimestamp  :: !UTCTime
  , messageModel      :: !(Maybe Text) -- Model used for assistant messages
  , messageProvider   :: !(Maybe Text) -- Provider used
  , messageTokensUsed :: !(Maybe Int)  -- Token count if available
  , messageError      :: !(Maybe Text) -- Error message if response failed
  } deriving (Eq, Show, Generic)

instance ToJSON Message
instance FromJSON Message

-- ════════════════════════════════════════════════════════════════
-- SESSION
-- ════════════════════════════════════════════════════════════════

-- | Conversation session
-- Note: ID is a UUID v4 stored as text
data Session = Session
  { sessionId           :: !Text         -- UUID v4 as text
  , sessionLanguageId   :: !Text
  , sessionMode         :: !Mode
  , sessionLearnerLevel :: !LearnerLevel
  , sessionCreatedAt    :: !UTCTime
  , sessionUpdatedAt    :: !UTCTime
  , sessionTitle        :: !(Maybe Text)
  , sessionActive       :: !Bool
  } deriving (Eq, Show, Generic)

instance ToJSON Session
instance FromJSON Session
